### ISSUE TITLE
pth格式问题

### ISSUE THREAD

**Issue by yin1112** [thu-nics/MNSIM-2.0#4]
1.系统环境

python3.6

pytorch版本1.5.1

2.生成pth数据的代码
  模型部分
	  class Lelnet1(torch.nn.Module):
		  def __init__(self):
			  super(Lelnet1,self).__init__()
			  self.conv1 = torch.nn.Conv2d(3,6,(5,5))
			  self.pool1 = torch.nn.MaxPool2d(2,2)	
			  self.conv2 = torch.nn.Conv2d(6,16,(5,5))
			  self.pool2 = torch.nn.MaxPool2d(2,2)
			  self.conv3 = torch.nn.Conv2d(16,1,(1,1))
			  self.fc1 = torch.nn.Linear(25,84)
			  self.fc2 = torch.nn.Linear(84,10)
	  model = Lelnet1()
  
  保存方式
     torch.save(model.state_dict(), './model.pth')
3.系统上的更改
  ![image](https://user-images.githubusercontent.com/55095824/125547325-5fddb6f2-f9e6-463e-9ab0-6968b570c1d8.png)
  
  在这里加上自己的网络和配置

4.运行之后产生的报错如下

![image](https://user-images.githubusercontent.com/55095824/125547456-2e3599da-eb77-4dae-9aa1-44783159bf5b.png)

请问要如何修改才可以跑通。

**Comment by cosineAlh** [comment]
你好，请问你还记得如何修改pth才能跑通自己的model吗，我现在遇到了相同的问题？

**Comment by yin1112** [comment]
我当时好像是单独写一个python文件加载权重，然后看key的名字修改后再导出

**Comment by cosineAlh** [comment]
非常感谢！请问如果可以的话，方便分享一下脚本吗？
